### ISSUE TITLE
not coloring root layout

### ISSUE THREAD

**Issue by marekyggdrasil** [statianzo/vim-jade#4]
My issue is that `vim-jade` correctly colors syntax on layouts that extend the root layout, but not root layout itself. Adding `extends` at beginning makes it work.

I used the manual installation method.

![zrzut ekranu z 2016-03-05 12 58 27](https://cloud.githubusercontent.com/assets/8202674/13545783/39bf97fa-e2d2-11e5-9270-6e2efd87c683.png)
![zrzut ekranu z 2016-03-05 12 58 57](https://cloud.githubusercontent.com/assets/8202674/13545784/39c5f776-e2d2-11e5-8b65-a9b5e9070138.png)

**Comment by statianzo** [comment]
You should use [vim-pug](https://github.com/digitaltoad/vim-pug) it's a maintained plugin for Pug (formerly Jade) syntax.
